mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webinar.urls')),
]

webinar/urls.py
from django.urls import path
from webinar.views import Index, thanks

app_name = 'webinar'

urlpatterns = [
    path('', Index.as_view(), name = 'index'),
    path('thanks/', thanks, name = 'thanks'),
]

webinar/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.
class JustUser(models.Model):
	fname = models.CharField(max_length = 30,verbose_name = 'First Name')
	lname = models.CharField(max_length = 30,verbose_name = 'Last Name')
	email = models.EmailField()
	mobile = PhoneNumberField()
	college = models.CharField(max_length = 30,verbose_name = 'College/Organization')
	profession = models.CharField(max_length = 30,verbose_name = 'Profession')

	def __str__(self):
		return self.fname+' '+self.lname

class JustEdit(models.Model):
	ref = models.CharField(max_length = 4)
	subject = models.CharField(max_length = 100)
	body = models.TextField()

	def __str__(self):
		return self.ref

webinar/forms.py
from django import forms
from django.forms import ModelForm
from webinar.models import JustUser

class UserForm(ModelForm):
	class Meta:
		model = JustUser
		fields = '__all__'

webinar/views.py
from django.shortcuts import render,HttpResponse
from webinar.forms import UserForm
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from webinar.models import JustEdit

# Create your views here.
class Index(FormView):
    template_name = 'index.html'
    form_class = UserForm
    success_url = '/thanks/'

    def form_valid(self, form):
        #to_mail = form.cleaned_data['email']
        #e = JustEdit.objects.get(ref = 'asdf')
        #sub = e.subject
        #msg = e.body
        #send_mail(sub ,msg ,'info@codegnan.com',[to_mail],fail_silently=False)
        form.save()
        return super().form_valid(form)

def thanks(request):
	return render(request,'thanks.html')

webinar/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Webinar</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>

<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'webinar:index' %}">
    <img src="https://codegnan.com/assets/img/codegnan-new01.png" width="200" height="50" alt="">
  </a>
</nav>

<div class="container">
	<br>
{% block content %}
{% endblock %}
</div>
    <br>
<footer class="footer">
      <div class="container">
        <span class="text-muted">@2020 copyrights reserved</span>
      </div>
</footer>
</body>
</html>

webinar/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-md-6">
    	
     	<img src="{% static 'img02.jpg' %}" class="img-fluid">
    </div>
    <div class="col-md-6">
    	<form method="post">{% csrf_token %}
    	{{ form|crispy }}
    	<input class="btn btn-outline-info" type="submit" value="Register">
		</form>
    </div>
</div>
{% endblock %}

webinar/templates/thanks.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div style="font-size: 20px">
<p><b>Thanks for Registration, Click the button below to subscribe to our Youtube Channel</b></p>

<script src="https://apis.google.com/js/platform.js"></script>

<div class="g-ytsubscribe" data-channelid="UCEZAhBBmxvUHaYkWB8J4Ltg" data-layout="default" data-count="default"></div>

<p>and hit bell icon to get notified of new updates</p>
<br>
<p>Webinar will be live on YouTube @07:00 PM</p>
<b><p><a href="https://www.youtube.com/watch?v=vxAn--41K5U">01-05-2020 Machine Learning with Scikit-Learn Webinar</a></p>
<p>Timings : 07:00 PM - 08:30 PM</p></b>
<br>
<p style="font-family: cursive;">p.s: Participants who have registered will receive certificate and material after the webinar</p>
</div>
{% endblock %}